ALTER VIEW dbo.view_DashTotalCaseVolume
AS
SELECT TOP 14
  DATEPART(YEAR, DOS)  AS Year,
  DATEPART(MONTH, DOS) AS Month,
  COUNT(CASE WHEN InsuranceType = 'Private'
    THEN 1
        ELSE NULL END) AS EligibleCases,
  COUNT(CASE WHEN InsuranceType = 'Other'
    THEN 1
        ELSE NULL END) AS Other
FROM View_PayerMix
WHERE (DOS >= DATEADD(MONTH, -14, DATEADD(MONTH, DATEDIFF(MONTH, 0, GETDATE()), 0)))
GROUP BY DATEPART(MONTH, DOS), DATEPART(YEAR, DOS)
ORDER BY DATEPART(YEAR, DOS), DATEPART(MONTH, DOS)
