create table TechCompanyLookup  ( 
					TechEntityLookupID int NOT NULL IDENTITY(1,1), 
					Surgeon  varchar(150) not null, 
					TechEntity varchar(150) not null, 
					StartDate date not null, 
					EndDate date not null, 
					Region varchar(50) not null)

select * from techcompanylookup

INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Brent Adcox, M.D.','Neuro Wave Physiology, LLC','2017-5-1','2020-12-31','Alaska')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Curtis Mina, M.D.','Neuro Wave Physiology, LLC','2017-1-1','2020-12-31','Alaska')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Amit Patel, M.D.','Lonestar, LLC','2017-5-1','2020-12-31','Arizona')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Dr. C Gilberto Brito, M.D.','Lonestar, LLC','2017-5-1','2020-12-31','Arizona')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Harvinder Bedi, M.D.','Lonestar, LLC','2017-1-1','2020-12-31','Arizona')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jeffrey Wingate, M.D.','Lonestar, LLC','2017-5-1','2020-12-31','Arizona')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Joshua Levy, D.O.','Lonestar, LLC','2017-1-1','2020-12-31','Arizona')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Kendrick Thomas, M.D.','Lonestar, LLC','2017-6-1','2020-12-31','Arizona')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Marc Letellier, M.D.','Lonestar, LLC','2017-1-1','2020-12-31','Arizona')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Thomas Raley, M.D.','No Tech Billing','2017-1-1','2020-12-31','California')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Hugh McPherson, M.D.','Cortico Spinal Diagnostics, LLC','2017-5-1','2020-12-31','Colorado')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('William Tally, M.D.','Gemini Health, LLC','2017-6-1','2020-12-31','Georgia-North')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Bernie McHugh, Jr., M.D.','Laser Accurate, LLC','2017-1-1','2020-12-31','Louisiana')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Dani Bidros, M.D.','Laser Accurate, LLC','2017-1-1','2020-12-31','Louisiana')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Eric Oberlander, M.D.','Laser Accurate, LLC','2017-1-12','2020-12-31','Louisiana')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Kevin McCarthy, M.D.','Laser Accurate, LLC','2017-1-12','2020-12-31','Louisiana')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Thomas Raley, M.D.','No Tech Billing','2017-1-1','2020-12-31','Maryland')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Adam Lewis, M.D.','Core Diagnostics, LLC','2017-5-1','2020-12-31','Mississippi - South')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Josue Gabriel, M.D.','Monument Diagnostics','2017-6-1','2020-12-31','Missouri')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Andrew Cash, M.D.','Neon Diagnostics, LLC','2017-6-1','2020-12-31','Nevada - Las Vegas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('George Kellis, M.D.','Over the Horizon IOM, LLC','2017-3-21','2020-12-31','Ohio')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jamal Taha, M.D.','Over the Horizon IOM, LLC','2017-3-21','2020-12-31','Ohio')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jon Paley, M.D.','Over the Horizon IOM, LLC','2017-3-21','2020-12-31','Ohio')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Josue Gabriel, M.D.','Over the Horizon IOM, LLC','2017-3-21','2020-12-31','Ohio')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Kamal Morar, M.D.','Over the Horizon IOM, LLC','2017-3-21','2020-12-31','Ohio')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Lance Tigyer, M.D.','Over the Horizon IOM, LLC','2017-3-21','2020-12-31','Ohio')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Mubin Syed, M.D.','Over the Horizon IOM, LLC','2017-3-21','2020-12-31','Ohio')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Andrew Parkinson, M.D.','Red River Neurodiagnostics, LLC','2017-5-26','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Arthur Conley, M.D.','Red River Neurodiagnostics, LLC','2017-5-1','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Blake Christensen, D.O.','Red River Neurodiagnostics, LLC','2017-4-1','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Brian Snell, M.D.','Cortex Neuromonitoring, LLC','2017-5-2','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Bridger Cox, M.D.','Red River Neurodiagnostics, LLC','2017-5-18','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Cheng-Lun Soo, M.D.','Red River Neurodiagnostics, LLC','2017-6-1','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Fadi Nasr, M.D.','Red River Neurodiagnostics, LLC','2017-6-1','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('James Odor, M.D.','Cortex Neuromonitoring, LLC','2017-4-18','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jimmy Conway, M.D.','Cortex Neuromonitoring, LLC','2017-5-1','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Lance Smith, M.D.','Red River Neurodiagnostics, LLC','2017-5-16','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Matthew Stanfield, M.D.','Red River Neurodiagnostics, LLC','2017-5-1','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Michael Hahn, M.D.','Cortex Neuromonitoring, LLC','2017-5-1','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Robert Remondino, M.D.','Cortex Neuromonitoring, LLC','2017-5-3','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Robert Tibbs, M.D.','Red River Neurodiagnostics, LLC','2017-5-1','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Robert Wienecke, M.D.','Red River Neurodiagnostics, LLC','2017-6-1','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Shon Cook, M.D.','Red River Neurodiagnostics, LLC','2017-5-4','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Winston Fong, M.D.','Red River Neurodiagnostics, LLC','2017-5-12','2020-12-31','Oklahoma')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Francisco Soldevilla, M.D.','Neuro Wave Physiology, LLC','2017-6-1','2020-12-31','Oregon')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Erik Gregorie, M.D.','Frontline Healthcare, LLC','2017-6-1','2020-12-31','Pennsylvania')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Matthew Quigley, M.D.','Frontline Healthcare, LLC','2017-6-1','2020-12-31','Pennsylvania')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Thomas Raley, M.D.','Frontline Healthcare, LLC','2017-6-1','2020-12-31','Pennsylvania')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Don Stovall, M.D.','Alpha Monitoring, LLC','2017-1-1','2020-12-31','South Carolina')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jason Highsmith, M.D.','Alpha Monitoring, LLC','2017-1-1','2020-12-31','South Carolina')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Mike Tyler, M.D.','Alpha Monitoring, LLC','2017-1-1','2020-12-31','South Carolina')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Sabino D''Agostino, D.O.','Alpha Monitoring, LLC','2017-1-25','2020-12-31','South Carolina')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('William Wilson, M.D.','Alpha Monitoring, LLC','2017-1-1','2020-12-31','South Carolina')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Carl Bischoff, M.D.','Shortwave Diagnostics, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('David Cuellar, M.D.','Shortwave Diagnostics, LLC','2017-5-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Gordon Marshall, M.D.','Delta Neuromonitoring, LLC','2017-5-23','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Hari Tumu, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Irvin K Sahni, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('James Smith, Jr., M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Manish Patel, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Michael Moghimi, M.D.','Neurophysiologic Interpretive Services, LLC','2017-2-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Mustasim Rumi, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Okay Onan, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Ram Vasudevan, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Randall Dryer, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Robert Josey, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Theodore Spinks, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Thomas Loftus, M.D.','Neurophysiologic Interpretive Services, LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Andrew Indresano, M.D.','Flexion Neuromonitoring, LLC','2017-4-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Andrew Park, M.D.','Neurite Monitoring, LLC','2017-5-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Benjamin Martino, M.D.','Flexion Neuromonitoring, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Bradford Bader, M.D.','Hypnic Diagnostics, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Brent Morgan, M.D.','Flexion Neuromonitoring, LLC','2017-1-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Brian Reece, M.D.','Flexion Neuromonitoring, LLC','2017-5-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Cameron Carmody, M.D.','Neurite Monitoring, LLC','2017-5-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Chad McDuffie, M.D.','Shortwave Diagnostics, LLC','2017-5-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Cherie Booth, M.D.','Flexion Neuromonitoring, LLC','2017-3-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Craig Callewart, M.D.','Neurite Monitoring, LLC','2017-3-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Dale Ehmer, M.D.','Shortwave Diagnostics, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('David Masel, M.D.','Neurite Monitoring, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Diana Wilson, M.D.','Hypnic Diagnostics, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Elijah Hothem, M.D.','Flexion Neuromonitoring, LLC','2017-5-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Eric Ray, M.D.','Physiologic Diagnostic Service, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Ewen Tseng, M.D.','Hypnic Diagnostics, LLC','2017-5-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Francisco Batlle, M.D.','Physiologic Diagnostic Service, LLC','2017-5-19','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jacob Rosenstein, M.D.','Physiologic Diagnostic Service, LLC','2017-4-7','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jason Taub, M.D.','Neurite Monitoring, LLC','2017-3-10','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jean Louis Benae, M.D.','Shortwave Diagnostics, LLC','2017-5-11','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jeff Phelps, M.D.','Hypnic Diagnostics, LLC','2017-4-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jeremy Denning, M.D.','Flexion Neuromonitoring, LLC','2017-4-29','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('John Tenny, M.D.','Shortwave Diagnostics, LLC','2017-4-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jon Krumerman, M.D.','Flexion Neuromonitoring, LLC','2017-4-4','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jonathan Fontenot, M.D.','Shortwave Diagnostics, LLC','2017-5-23','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Joseph Tejan, M.D.','Neurite Monitoring, LLC','2017-4-12','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Joshua James, M.D.','Flexion Neuromonitoring, LLC','2017-5-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Keith Preston, M.D.','Shortwave Diagnostics, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Kendall Carll, M.D.','Hypnic Diagnostics, LLC','2017-5-2','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Kenneth Hsu, M.D.','Flexion Neuromonitoring, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Kevin James, M.D.','Hypnic Diagnostics, LLC','2017-5-11','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Kevin Kaufman, M.D.','Physiologic Diagnostic Service, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Larry Kjeldgaard, D.O.','Hypnic Diagnostics, LLC','2017-4-4','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Lav Kapadia, M.D.','Shortwave Diagnostics, LLC','2017-5-19','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Lewis Frazier, M.D.','Hypnic Diagnostics, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Mark Silver, M.D.','Flexion Neuromonitoring, LLC','2017-5-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Melanie Kinchen, M.D.','Shortwave Diagnostics, LLC','2017-4-4','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Michael Desaloms, M.D.','Delta Neuromonitoring, LLC','2017-3-21','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Michael Hennessy, M.D.','Hypnic Diagnostics, LLC','2017-4-8','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Neal Haynes, M.D.','Physiologic Diagnostic Service, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Neelesh Mehendale, M.D.','Shortwave Diagnostics, LLC','2017-5-24','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Nimish Patel, M.D.','Flexion Neuromonitoring, LLC','2017-4-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Rebecca Stachniak, M.D.','Physiologic Diagnostic Service, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Richard Burg, M.D.','Shortwave Diagnostics, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Richard Marks, M.D.','Neurite Monitoring, LLC','2017-5-6','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Richard Thrasher, M.D.','Flexion Neuromonitoring, LLC','2017-4-26','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Robert Spicer, M.D.','Hypnic Diagnostics, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Robert Viere, M.D.','Neurite Monitoring, LLC','2017-4-13','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Saeid Aryan, D.O.','Flexion Neuromonitoring, LLC','2017-4-25','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Samir Parikh, M.D.','Physiologic Diagnostic Service, LLC','2017-1-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Saqib Siddiqui, M.D.','Synergy Neuromonitoring, LLC','2017-1-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Sean Jones-Quaidoo, M.D.','Shortwave Diagnostics, LLC','2017-2-11','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Shamim Badiyan, M.D.','Hypnic Diagnostics, LLC','2017-4-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Shane Pahlavan, M.D.','Flexion Neuromonitoring, LLC','2017-4-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Stephen Courtney, M.D.','Flexion Neuromonitoring, LLC','2017-4-4','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Stephen Neece, M.D.','Physiologic Diagnostic Service, LLC','2017-1-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Steven Remer, M.D.','Shortwave Diagnostics, LLC','2017-6-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Vudhi Slabisak, M.D.','Synergy Neuromonitoring, LLC','2017-5-27','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Navin Subramanian, M.D.','Apex Health Monitoring, LLC','2017-5-6','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Thomas Jones, M.D.','Apex Health Monitoring, LLC','2017-1-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Vivek Kushwaha, M.D.','Apex Health Monitoring, LLC','2017-1-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Amir Malik, M.D.','Synergy Neuromonitoring, LLC','2017-6-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Anthony Owusu, M.D.','Apex Health Monitoring, LLC','2017-3-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Baraa Al-Hafez, M.D.','Synergy Neuromonitoring, LLC','2017-5-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Devinder Bhatia, M.D.','Synergy Neuromonitoring, LLC','2017-2-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Ian Reynolds, M.D.','Synergy Neuromonitoring, LLC','2017-2-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jeremy Wang, M.D.','Synergy Neuromonitoring, LLC','2017-1-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Neal Haynes, M.D.','Apex Health Monitoring, LLC','2017-4-19','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Rajesh Bindal, M.D.','Synergy Neuromonitoring, LLC','2017-1-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Richard Westmark, M.D.','Synergy Neuromonitoring, LLC','2017-1-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Saqib Siddiqui, M.D.','Synergy Neuromonitoring, LLC','2017-1-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Stanley Jones, M.D.','Synergy Neuromonitoring, LLC','2017-1-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Stuart Weil, M.D.','Synergy Neuromonitoring, LLC','2017-1-1','2020-12-31','Texas - Houston')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Adam Bruggeman, M.D.','National Neuromonitoring Services, LLC','2017-1-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Adewale Adeniran, M.D.','National Neuromonitoring Services, LLC','2017-1-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Ajeya Joshi, M.D.','Cerebri Monitoring, LLC','2017-3-28','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Alec Stall, M.D.','Cerebri Monitoring, LLC','2017-1-11','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Anthony Owusu, M.D.','National Neuromonitoring Services, LLC','2017-5-19','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Arnold Vardiman, M.D.','National Neuromonitoring Services, LLC','2017-4-18','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Charles Pipkin, M.D.','National Neuromonitoring Services, LLC','2017-5-17','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('David Roberts, M.D.','National Neuromonitoring Services, LLC','2017-1-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Ed Anderson, M.D.','National Neuromonitoring Services, LLC','2017-6-10','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Elizabeth Magnabosco, M.D.','Cerebri Monitoring, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Frank Kuwamura, M.D.','Cerebri Monitoring, LLC','2017-4-25','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('George Galvan, M.D.','Cerebri Monitoring, LLC','2017-5-3','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Gilbert Meadows, M.D.','National Neuromonitoring Services, LLC','2017-6-14','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Gregg Gurwitz, M.D.','National Neuromonitoring Services, LLC','2017-4-13','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Hongbo Liu, M.D.','Mission Diagnostics, LLC','2017-4-8','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Irvin K Sahni, M.D.','Mission Diagnostics, LLC','2017-3-21','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('James Simmons, III, M.D.','Cerebri Monitoring, LLC','2017-4-27','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jerjis Denno, M.D.','Cerebri Monitoring, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Joel Jenne','Cerebri Monitoring, LLC','2017-5-13','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jonathan Duncan, M.D.','National Neuromonitoring Services, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Juan Martin, M.D.','Synergy Neuromonitoring, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Kevin Richardson, D.O.','Mission Diagnostics, LLC','2017-5-4','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Kimberly Terry, M.D.','Cerebri Monitoring, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Lance Jackson, M.D.','National Neuromonitoring Services, LLC','2017-5-19','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Micam Tullous, M.D.','Cerebri Monitoring, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Michael David Dennis, M.D.','Cerebri Monitoring, LLC','1901-6-7','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Michael Leonard, M.D.','Mission Diagnostics, LLC','2017-3-22','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Naveen Kella, M.D.','Mission Diagnostics, LLC','2017-4-18','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Pablo Vazquez-Seoane, M.D.','National Neuromonitoring Services, LLC','2017-4-25','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Patricia Mancuso, M.D.','Cerebri Monitoring, LLC','2017-4-4','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Paul Geibel, M.D.','Cerebri Monitoring, LLC','2017-5-11','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Ralph Garza, M.D.','Cerebri Monitoring, LLC','2017-3-11','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Ram Vasudevan, M.D.','Mission Diagnostics, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Robert Thomas, M.D.','Cerebri Monitoring, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('William Koeck, M.D.','Cerebri Monitoring, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('William Tisdall, M.D.','Cerebri Monitoring, LLC','2017-6-1','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Robert Urrea, M.D.','El Paso Monitoring, LLC','2017-1-18','2020-12-31','Texas - West Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Gordon Yee, M.D.','Neuro Wave Physiology, LLC','2017-6-1','2020-12-31','Washington')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Jorge Alvernia, M.D.','Laser Accurate, LLC','2017-1-13','2020-12-31','Louisiana')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Eubulus Kerr, M.D.','Laser Accurate, LLC','2017-1-13','2020-12-31','Louisiana')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Andrew Utter, M.D.','Laser Accurate, LLC','2017-1-13','2020-12-31','Louisiana')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Pierce Nunley, M.D.','Laser Accurate, LLC','2017-1-13','2020-12-31','Louisiana')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Martin Bertram, M.D.','Over the Horizon IOM, LLC','2017-3-1','2020-12-31','Ohio')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Mark Grubb, M.D.','Over the Horizon IOM, LLC','2017-3-1','2020-12-31','Ohio')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Presley Mock, M.D.','Physiologic Diagnostic Service, LLC','2017-1-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Chris Lee, M.D.','Physiologic Diagnostic Service, LLC','2017-1-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Rene Pena, M.D.','Physiologic Diagnostic Service, LLC','2017-1-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Stuart Thomas, M.D.','Physiologic Diagnostic Service, LLC','2017-1-1','2020-12-31','Texas - DFW')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Desh Sahni, M.D.','Neurophysiologic Interpretive Services LLC','2017-1-1','2020-12-31','Texas - Austin')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Shiela Smitherman, M.D.','Neuro Wave Physiology, LLC','2017-1-1','2020-12-31','Washington')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Melvin Wahl, M.D.','Neuro Wave Physiology, LLC','2017-1-1','2020-12-31','Washington')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Brian Iuliano, M.D.','Neuro Wave Physiology, LLC','2017-1-1','2020-12-31','Washington')

--ticket 2211 naz

select * from techcompanylookup
select * from techcompanylookup where techentitylookupid = 194
select * from techcompanylookup where surgeon like '%paymaun%'
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) VALUES ('Paymaun Lotfi, M.D.','Colony Diagnostics, LLC','2017-07-31','2020-12-31','Virginia')

--ticket 2273 lauren

select * from techcompanylookup where techentitylookupid in (142,154,170,155)
update TechCompanyLookup set EndDate = '2017-08-31' where TechEntityLookupID in (142,154,170,155)
select * from techcompanylookup where surgeon in('Adam Bruggeman, M.D.','Gilbert Meadows, M.D.','Pablo Vazquez-Seoane, M.D.','Gregg Gurwitz, M.D.')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) 
	VALUES ('Adam Bruggeman, M.D.','Mission Diagnostics, LLC','2017-09-01','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) 
	VALUES ('Gilbert Meadows, M.D.','Mission Diagnostics, LLC','2017-09-01','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) 
	VALUES ('Pablo Vazquez-Seoane, M.D.','Mission Diagnostics, LLC','2017-09-01','2020-12-31','Texas - South Texas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) 
	VALUES ('Gregg Gurwitz, M.D.','Mission Diagnostics, LLC','2017-09-01','2020-12-31','Texas - South Texas')

--ticket 2290 naz
select * from techcompanylookup where surgeon in ('Gerard Librodo, M.D.','Sharma Vivek, M.D.')

INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) 
	VALUES ('Gerard Librodo, M.D.','Arch Diagnostics, LLC','2017-7-31','2020-12-31','Kansas')
INSERT INTO TechCompanyLookup (Surgeon, TechEntity,StartDate,EndDate,Region) 
	VALUES ('Sharma Vivek, M.D.','Arch Diagnostics, LLC','2017-7-31','2020-12-31','Kansas')